[Desktop Entry]
Type=X-GNOME-Metatheme
Name=z0mbi3Night-zk
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=z0mbi3Night-zk
GtkTheme=z0mbi3Night-zk
IconTheme=z0mbi3Night-zk
MetacityTheme=z0mbi3Night-zk
